baseurl = "https://summit360-web.netlify.com"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Summit 360"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Outdoor IT Specialist"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

# [[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
# [[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
# [[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Colin Densem"
  email = "hello@summit360.co.uk"
  gitlab = "colindensem"
  github = "colindensem"
  twitter = "colindensem"


[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
[[menu.main]]
    name = "Contact"
    url = "page/contact/"
    weight = 3


[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "Go Outdoors"
    url = "post/2013-03-01-gooutdoors"
    weight = 1

[[menu.main]]
    parent = "projects"
    name = "BRISKODA"
    url = "post/2002-10-31-briskoda"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "Climbers Club"
    url = "post/2014-06-18-climbers-club"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
